
name: CI-dev-pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - uses: actions/checkout@v2
        with:
          path: "gaint_backend"

      - name: Build docker
        run: |
          echo Hello, world!
          docker --version
          echo version  
          echo --Building and starting up docker--
          docker-compose -f ./gaint_backend/docker-compose.yml -f ./gaint_backend/docker-compose.dev.yml up
          echo === Complete test Case ===
      - name: Run test
        run: |
          echo -- test--
      - name : Extract commit
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)"  >> $GITHUB_ENV
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV



